services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile.backend
    dockerCommand: "java -jar app.jar"
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: portfolio-frontend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile.frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://portfolio-backend:8080
